version: "3"

services:
  database-gamification:
    image: postgres:alpine
    restart: always
    expose:
      - 8232
    ports:
      - "8232:5432"
    volumes:
      - gamificationdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gamification_service
  app-gamification:
    build:
      context: ./../gamification_service # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: always
    container_name: gamification_service
    expose:
      - 8200
      - 8201
    ports:
      - "8200:8200"
      - "8201:8201"
    depends_on:
      - database-gamification
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-gamification:5432/gamification_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-gamification:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "gamification_service",
      "--app-port", "8201",
      "--dapr-http-port", "8200",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../gamification_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-gamification
      - redis
    network_mode: "service:app-gamification"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  gamificationdata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true